"""add sync retry columns

Revision ID: 2d016c736084
Revises: f5958fdbf27b
Create Date: 2026-07-02 16:54:02.410927
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2d016c736084'
down_revision: Union[str, None] = 'f5958fdbf27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_integrations', sa.Column('sync_failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('google_integrations', sa.Column('next_sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_integrations', 'next_sync_at')
    op.drop_column('google_integrations', 'sync_failures')
    # ### end Alembic commands ###
